<div style="display: flex; align-items: center; justify-content: space-between;">
    <div>
        <h1 style="font-weight: bold; font-size: 50px;">HR Analytics</h1>
        <h2 style="font-weight: bold; font-size: 26px;">Submitted By:</h2>
        <p style="font-size: 15px;">
            Sarah Mohammed Mahmoud Ebied<br>
            Bishoy Kamal Ragheb Nakhla <br>
            Hossam Hassan Mohamed Abo-Al Ela <br>
            Omar Salah El-dien Saad Mutawe <br>
            Hazem Gamal Abdelnaser Mohamed <br>
            Mohsen Salah Abd-ElKarim Shahat <br>


        </p>
    </div>
    <div style="margin-left: 550px;">
        <img src="/Users/godzilla/Desktop/Sara/DEPI.png" alt="Image" style="width: 200px;">
    </div>
</div>


# 1- Importing Libraries

In [2]:
import numpy as np 
import pandas as pd 

# 2- Reading Data 

In [9]:
# Reading Employee File
employee_df = pd.read_excel('D:\\Sarah\\ماتيريال منحة رواد مصر\\Final project\\Employee.xlsx')

# Reading Education Level File
education_df = pd.read_excel('D:\\Sarah\\ماتيريال منحة رواد مصر\\Final project\\EducationLevel.xlsx', engine='openpyxl')

# Reading Rating Level File
rating_df = pd.read_excel('D:\\Sarah\\ماتيريال منحة رواد مصر\\Final project\\RatingLevel.xlsx', engine='openpyxl')

# Reading Satisfied Level File
satisfied_df = pd.read_excel('D:\\Sarah\\ماتيريال منحة رواد مصر\\Final project\\SatisfiedLevel.xlsx', engine='openpyxl')

# Reading Performance Rating File
performance_df = pd.read_excel('D:\\Sarah\\ماتيريال منحة رواد مصر\\Final project\\PerformanceRating.xlsx', engine='openpyxl')


# 3- Explatory Data Analysis

## 3.1- Employee

In [122]:
# Printing first 5 Rows
employee_df.head(5)

EmployeeID   FirstName LastName      Gender  Age BusinessTravel  \
0  3012-1A41    Leonelle    Simco      Female   30    Some Travel   
1  CBCB-9C9D     Leonerd    Aland        Male   38    Some Travel   
2  95D7-1CE9       Ahmed    Sykes        Male   43    Some Travel   
3  47A0-559B  Ermentrude   Berrie  Non-Binary   39    Some Travel   
4  42CC-040A       Stace   Savege      Female   29    Some Travel   

        Department  DistanceFromHome (KM) State                Ethnicity  ...  \
0            Sales                     27    IL                    White  ...   
1            Sales                     23    CA                    White  ...   
2  Human Resources                     29    CA  Asian or Asian American  ...   
3       Technology                     12    IL                    White  ...   
4  Human Resources                     29    CA                    White  ...   

   MaritalStatus  Salary StockOptionLevel OverTime   HireDate  Attrition  \
0       Divorced  102059                1       No 2012-01-03         No   
1         Single  157718                0      Yes 2012-01-04         No   
2        Married  309964                1       No 2012-01-04         No   
3        Married  293132                0       No 2012-01-05         No   
4         Single   49606                0       No 2012-01-05        Yes   

  YearsAtCompany YearsInMostRecentRole YearsSinceLastPromotion  \
0             10                     4                       9   
1             10                     6                      10   
2             10                     6                      10   
3             10                    10                      10   
4              6                     1                       1   

   YearsWithCurrManager  
0                     7  
1                     0  
2                     8  
3                     0  
4                     6  

[5 rows x 23 columns]

In [123]:
# Show the number of rows and columns
employee_df.shape


(1470, 23)

In [124]:
# Showing the column names
employee_df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'Gender', 'Age',
       'BusinessTravel', 'Department', 'DistanceFromHome (KM)', 'State',
       'Ethnicity', 'Education', 'EducationField', 'JobRole', 'MaritalStatus',
       'Salary', 'StockOptionLevel', 'OverTime', 'HireDate', 'Attrition',
       'YearsAtCompany', 'YearsInMostRecentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [125]:
# Checking the data types of each column
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   EmployeeID               1470 non-null   object        
 1   FirstName                1470 non-null   object        
 2   LastName                 1470 non-null   object        
 3   Gender                   1470 non-null   object        
 4   Age                      1470 non-null   int64         
 5   BusinessTravel           1470 non-null   object        
 6   Department               1470 non-null   object        
 7   DistanceFromHome (KM)    1470 non-null   int64         
 8   State                    1470 non-null   object        
 9   Ethnicity                1470 non-null   object        
 10  Education                1470 non-null   int64         
 11  EducationField           1470 non-null   object        
 12  JobRole                  1470 non-

In [126]:
# Checking the number of null values.
employee_df.isnull().sum()

EmployeeID                 0
FirstName                  0
LastName                   0
Gender                     0
Age                        0
BusinessTravel             0
Department                 0
DistanceFromHome (KM)      0
State                      0
Ethnicity                  0
Education                  0
EducationField             0
JobRole                    0
MaritalStatus              0
Salary                     0
StockOptionLevel           0
OverTime                   0
HireDate                   0
Attrition                  0
YearsAtCompany             0
YearsInMostRecentRole      0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [127]:
# Checking the number of duplicates.
print(employee_df.duplicated().sum())

0


# 4- Data Cleaning

## 4.1- Employee

#### 4.1.1- Gender Column

In [18]:
# Print unique genders
print(employee_df["Gender"].unique())


['Female' 'Male' 'Non-Binary' 'Prefer Not To Say']


#### 4.1.2- Business Travel Column

In [129]:
# Print unique business travel
print(employee_df["BusinessTravel"].unique())


['Some Travel' 'No Travel ' 'Frequent Traveller']


In [130]:
# Removing trailing spaces
employee_df["BusinessTravel"] = employee_df["BusinessTravel"].str.strip()

#### 4.1.3- Department Column

In [131]:
# Print unique departments
print(employee_df["Department"].unique())


['Sales' 'Human Resources' 'Technology']


#### 4.1.4- State Column

In [132]:
# Print unique state
print(employee_df["State"].unique())


['IL' 'CA' 'NY']


#### 4.1.5- Ethnicity Column

In [133]:
# Print unique ethnicity
print(employee_df["Ethnicity"].unique())


['White' 'Asian or Asian American' 'Mixed or multiple ethnic groups'
 'Black or African American' 'Native Hawaiian ' 'Other '
 'American Indian or Alaska Native']


In [134]:
# Removing trailing spaces
employee_df["Ethnicity"] = employee_df["Ethnicity"].str.strip()

# Replace "Asian or Asian American" with "Asian American" 
employee_df["Ethnicity"] = employee_df["Ethnicity"].replace("Asian or Asian American", "Asian American")

# Simplify "Mixed or multiple ethnic groups" to "Mixed" 
employee_df["Ethnicity"] = employee_df["Ethnicity"].replace("Mixed or multiple ethnic groups", "Mixed")

# Shorten "Black or African American" to "Black American" 
employee_df["Ethnicity"] = employee_df["Ethnicity"].replace("Black or African American", "Black American")

# Change "American Indian or Alaska Native" to "Indian American"
employee_df["Ethnicity"] = employee_df["Ethnicity"].replace("American Indian or Alaska Native", "Indian American")

print(employee_df["Ethnicity"].unique())


['White' 'Asian American' 'Mixed' 'Black American' 'Native Hawaiian'
 'Other' 'Indian American']


#### 4.1.6- Education Column

In [135]:
print(employee_df["Education"].unique())


[5 4 3 2 1]


In [136]:
# Mapping education number with level values
employee_df["Education"] = employee_df["Education"].replace(1, "No Formal Qualifications")
employee_df["Education"] = employee_df["Education"].replace(2, "High School")
employee_df["Education"] = employee_df["Education"].replace(3, "Bachelors")
employee_df["Education"] = employee_df["Education"].replace(4, "Masters")
employee_df["Education"] = employee_df["Education"].replace(5, "Doctorate")


print(employee_df["Education"].unique())


['Doctorate' 'Masters' 'Bachelors' 'High School'
 'No Formal Qualifications']


#### 4.1.7- Education Field Column

In [137]:
# Print unique education fields
print(employee_df["EducationField"].unique())


['Marketing' 'Marketing ' 'Computer Science' 'Technical Degree'
 'Information Systems' 'Other' 'Economics' 'Human Resources'
 'Business Studies']


In [138]:
# Removing trailing spaces
employee_df["EducationField"] = employee_df["EducationField"].str.strip()

# Replacing both informatio systems and technical degree with computer science 
employee_df["EducationField"] = employee_df["EducationField"].replace("Information Systems", "Computer Science")
employee_df["EducationField"] = employee_df["EducationField"].replace("Technical Degree", "Computer Science")


print(employee_df["EducationField"].unique())


['Marketing' 'Computer Science' 'Other' 'Economics' 'Human Resources'
 'Business Studies']


#### 4.1.8- Marital Status Column

In [139]:
# Print unique marital status
print(employee_df["MaritalStatus"].unique())


['Divorced' 'Single' 'Married']


#### 4.1.9- Over Time Column

In [140]:
# Print unique over-time
print(employee_df["OverTime"].unique())


['No' 'Yes']


#### 4.1.10- Age Column

In [141]:
# Print sorted unique ages
print(sorted(employee_df["Age"].unique().tolist()))

[18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]


In [142]:
# Define bins for grouping
bins = [0, 25, 35, 45, 100]  
labels = ['18-24', '25-34', '35-44', '45+']  

# Create the AgeGroup column
employee_df["AgeGroup"] = pd.cut(employee_df['Age'], bins=bins, labels=labels, right=False)

# Insert AgeGroup column right after Age column
employee_df.insert(5, "AgeGroup", employee_df.pop("AgeGroup"))

#### 4.1.11- Name Column

In [143]:
# Concatenating both splitted names into a single full name 
employee_df["EmployeeName"] =  employee_df['FirstName'] + ' ' + employee_df['LastName']

# Insert EmployeeName after EmployeeID
employee_df.insert(1, "EmployeeName", employee_df.pop("EmployeeName"))

# Drop the splited names
employee_df = employee_df.drop(columns=['FirstName', 'LastName'])


In [145]:
employee_df.head(5)

EmployeeID       EmployeeName      Gender  Age AgeGroup BusinessTravel  \
0  3012-1A41     Leonelle Simco      Female   30    25-34    Some Travel   
1  CBCB-9C9D      Leonerd Aland        Male   38    35-44    Some Travel   
2  95D7-1CE9        Ahmed Sykes        Male   43    35-44    Some Travel   
3  47A0-559B  Ermentrude Berrie  Non-Binary   39    35-44    Some Travel   
4  42CC-040A       Stace Savege      Female   29    25-34    Some Travel   

        Department  DistanceFromHome (KM) State       Ethnicity  ...  \
0            Sales                     27    IL           White  ...   
1            Sales                     23    CA           White  ...   
2  Human Resources                     29    CA  Asian American  ...   
3       Technology                     12    IL           White  ...   
4  Human Resources                     29    CA           White  ...   

  MaritalStatus  Salary StockOptionLevel OverTime   HireDate  Attrition  \
0      Divorced  102059                1       No 2012-01-03         No   
1        Single  157718                0      Yes 2012-01-04         No   
2       Married  309964                1       No 2012-01-04         No   
3       Married  293132                0       No 2012-01-05         No   
4        Single   49606                0       No 2012-01-05        Yes   

  YearsAtCompany YearsInMostRecentRole YearsSinceLastPromotion  \
0             10                     4                       9   
1             10                     6                      10   
2             10                     6                      10   
3             10                    10                      10   
4              6                     1                       1   

   YearsWithCurrManager  
0                     7  
1                     0  
2                     8  
3                     0  
4                     6  

[5 rows x 23 columns]

#### 3.2- Performance


In [12]:
# Printing first 5 Rows
performance_df.head(5)

PerformanceID EmployeeID           ReviewDate  EnvironmentSatisfaction  \
0          PR01  79F7-78EC  2013-02-01 00:00:00                        5   
1          PR02  B61E-0F26  2013-03-01 00:00:00                        5   
2          PR03  F5E3-48BB  2013-03-01 00:00:00                        3   
3          PR04  0678-748A  2013-04-01 00:00:00                        5   
4          PR05  541F-3E19  2013-04-01 00:00:00                        5   

   JobSatisfaction  RelationshipSatisfaction  TrainingOpportunitiesWithinYear  \
0                4                         5                                1   
1                4                         4                                1   
2                4                         5                                3   
3                3                         2                                2   
4                2                         3                                1   

   TrainingOpportunitiesTaken  WorkLifeBalance  SelfRating  ManagerRating  
0                           0                4           4              4  
1                           3                4           4              3  
2                           2                3           5              4  
3                           0                2           3              2  
4                           0                4           4              3

In [13]:
# Checking the number of duplicates.
print(performance_df.duplicated().sum())

0


In [14]:
# Showing the column names
performance_df.columns


Index(['PerformanceID', 'EmployeeID', 'ReviewDate', 'EnvironmentSatisfaction',
       'JobSatisfaction', 'RelationshipSatisfaction',
       'TrainingOpportunitiesWithinYear', 'TrainingOpportunitiesTaken',
       'WorkLifeBalance', 'SelfRating', 'ManagerRating'],
      dtype='object')

In [15]:
# Checking the data types of each column
performance_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6709 entries, 0 to 6708
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   PerformanceID                    6709 non-null   object
 1   EmployeeID                       6709 non-null   object
 2   ReviewDate                       6709 non-null   object
 3   EnvironmentSatisfaction          6709 non-null   int64 
 4   JobSatisfaction                  6709 non-null   int64 
 5   RelationshipSatisfaction         6709 non-null   int64 
 6   TrainingOpportunitiesWithinYear  6709 non-null   int64 
 7   TrainingOpportunitiesTaken       6709 non-null   int64 
 8   WorkLifeBalance                  6709 non-null   int64 
 9   SelfRating                       6709 non-null   int64 
 10  ManagerRating                    6709 non-null   int64 
dtypes: int64(8), object(3)
memory usage: 576.7+ KB


In [16]:
# Checking the number of null values.
performance_df.isnull().sum()

PerformanceID                      0
EmployeeID                         0
ReviewDate                         0
EnvironmentSatisfaction            0
JobSatisfaction                    0
RelationshipSatisfaction           0
TrainingOpportunitiesWithinYear    0
TrainingOpportunitiesTaken         0
WorkLifeBalance                    0
SelfRating                         0
ManagerRating                      0
dtype: int64

In [17]:
# Checking the number of duplicates.
print(performance_df.duplicated().sum())

0


# 4.2- Data Cleaning

## 4.2.1- PerformanceID


In [19]:
# Print unique PerformanceID
print(performance_df["EmployeeID"].unique())



['79F7-78EC' 'B61E-0F26' 'F5E3-48BB' ... 'AAD7-8DDC' 'A2AE-FD61'
 'D6BA-10A1']


## 4.2.2- EmployeeID



In [20]:
# Print unique EmployeeID
print(performance_df["EmployeeID"].unique())



['79F7-78EC' 'B61E-0F26' 'F5E3-48BB' ... 'AAD7-8DDC' 'A2AE-FD61'
 'D6BA-10A1']


#### 4.2.3- ReviewDate


In [22]:
# Print unique ReviewDate
print(performance_df["ReviewDate"].unique())



[datetime.datetime(2013, 2, 1, 0, 0) datetime.datetime(2013, 3, 1, 0, 0)
 datetime.datetime(2013, 4, 1, 0, 0) ... '3/13/2016' '3/14/2016'
 '3/15/2016']


In [33]:
performance_df['ReviewDate'] = pd.to_datetime(performance_df['ReviewDate'], errors='coerce')


#### 4.2.4- EnvironmentSatisfaction


In [24]:
# Print unique EnvironmentSatisfaction
print(performance_df["EnvironmentSatisfaction"].unique())

[5 3 4 1 2]


#### 4.2.5- JobSatisfaction

In [25]:
# Print unique JobSatisfaction
print(performance_df["JobSatisfaction"].unique())


[4 3 2 5 1]


#### 4.2.6- RelationshipSatisfaction

In [26]:
# Print unique RelationshipSatisfaction
print(performance_df["RelationshipSatisfaction"].unique())

[5 4 2 3 1]


In [34]:
columns_to_check = [
    'EnvironmentSatisfaction', 
    'JobSatisfaction', 
    'RelationshipSatisfaction', 
    'WorkLifeBalance', 
    'SelfRating', 
    'ManagerRating'
]

for col in columns_to_check:
    out_of_range = performance_df[(performance_df[col] < 1) | (performance_df[col] > 5)]
    if not out_of_range.empty:
        print(f"Out-of-range values in {col}:")
        print(out_of_range)


#### 4.2.7- TrainingOpportunitiesWithinYear

In [27]:
# Print unique TrainingOpportunitiesWithinYear
print(performance_df["TrainingOpportunitiesWithinYear"].unique())

[1 3 2]


#### 4.2.8- TrainingOpportunitiesTaken

In [28]:
# Print unique TrainingOpportunitiesTaken
print(performance_df["TrainingOpportunitiesTaken"].unique())


[0 3 2 1]


In [35]:
inconsistent_rows = performance_df[performance_df['TrainingOpportunitiesTaken'] > performance_df['TrainingOpportunitiesWithinYear']]
if not inconsistent_rows.empty:
    print("Inconsistent training opportunities found:")
    print(inconsistent_rows)


Inconsistent training opportunities found:
     PerformanceID EmployeeID ReviewDate  EnvironmentSatisfaction  \
1             PR02  B61E-0F26 2013-03-01                        5   
9             PR10  774E-685D 2013-11-01                        5   
15          PR1004  DEC5-9319 2016-03-18                        3   
23          PR1011  5160-53BD 2016-03-24                        4   
30          PR1018  C525-8BB9 2016-03-27                        3   
...            ...        ...        ...                      ...   
6668         PR962  17AD-99F5 2016-01-03                        3   
6678         PR971  0322-D46B 2016-03-03                        5   
6680         PR973  1054-9C3B 2016-05-03                        4   
6693         PR985  40A9-8EB0 2016-09-03                        4   
6695         PR987  B005-602F 2016-10-03                        5   

      JobSatisfaction  RelationshipSatisfaction  \
1                   4                         4   
9                   4     

#### 4.2.9- WorkLifeBalance

In [29]:
# Print unique WorkLifeBalance
print(performance_df["WorkLifeBalance"].unique())

[4 3 2 5 1]


#### 4.2.10- SelfRating

In [30]:
# Print SelfRating
print(performance_df["SelfRating"].unique())


[4 5 3]


#### 4.2.11- ManagerRating

In [31]:
# Print ManagerRating
print(performance_df["ManagerRating"].unique())


[4 3 2 5]
